dist: xenial

compiler:
- g++


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - clang
    - check
    - libqd-dev
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

before_script:
- autoreconf -i

script:
- ./configure --enable-gmp --enable-mpfr --enable-qd --enable-dd --enable-double --enable-__float128 --enable-longdouble --enable-optimization --with-system-gmp --with-system-mpfr --with-system-mpc --with-system-qd
#- make -j${CPU_COUNT}
#- make
#- make check


before_deploy:
- make dist-gzip
- make dist-zip
- export DIST_GZIP=$(ls mlapack-*.tar.gz)
- export DIST_ZIP=$(ls mlapack-*.zip)
- echo "Deploying autoconf's dists (${DIST_GZIP} and ${DIST_ZIP}) to GitHub releases"


deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file:
  - "${DIST_GZIP}"
  - "${DIST_ZIP}"
  on:
    repo: RaumZeit/mlapack
    tags: true
